//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESONGEntities4 : DbContext
    {
        public ESONGEntities4()
            : base("name=ESONGEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SORTIRAJ_Result> GetPRIKAZ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SORTIRAJ_Result>("GetSORTIRAJ");
        }
    
        public virtual ObjectResult<SORTIRAJ_Result> GetSORTIRAJ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SORTIRAJ_Result>("GetSORTIRAJ");
        }
    }
}
